apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-lambda
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: claim
    repoURL: https://github.com/salesdemocf/lambda-processor-app
    targetRevision: HEAD
